### ISSUE TITLE
I cant register

### ISSUE THREAD

**Issue by IamSigma69** [BrettOrmsby/Sprout-PvZHeroes#7]
Hello, I hope this question hasnt been asked before, but i cant register. it says account not authorized. is there anything to bypass this? Because my friend can make an account smoothly and i dont

**Comment by Normal-Tangerine8609** [comment]
Unfortunately the library I used for Authentication has changed their policy for emails and they will no longer send them. This means no more signing up users or changing passwords. I am unable to get a free email sending service that integrates into the library, so I can't fix the issue. Sorry about that.

**Comment by IamSigma69** [comment]
Is there no any way?

**Comment by BrettOrmsby** [comment]
I have had some free time recently and was able to create a sign in with Discord method. This method may not be perfect, but it works. To change your username after, you can go to your decks and click the username and then change it to a unique one of your choice.
